# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mortalcoder/Documentos/GitHub/MyProyects/NoCodePython/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1056, 660)
        self.codeSpace = QtWidgets.QTextEdit(main)
        self.codeSpace.setGeometry(QtCore.QRect(10, 20, 661, 611))
        self.codeSpace.setObjectName("codeSpace")
        self.save_py_select = QtWidgets.QRadioButton(main)
        self.save_py_select.setGeometry(QtCore.QRect(685, 470, 91, 23))
        self.save_py_select.setObjectName("save_py_select")
        self.buttonGroup = QtWidgets.QButtonGroup(main)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.save_py_select)
        self.save_mdw_select = QtWidgets.QRadioButton(main)
        self.save_mdw_select.setGeometry(QtCore.QRect(775, 470, 91, 23))
        self.save_mdw_select.setObjectName("save_mdw_select")
        self.buttonGroup.addButton(self.save_mdw_select)
        self.saveButton = QtWidgets.QPushButton(main)
        self.saveButton.setGeometry(QtCore.QRect(890, 450, 71, 61))
        self.saveButton.setObjectName("saveButton")
        self.exitButton = QtWidgets.QPushButton(main)
        self.exitButton.setGeometry(QtCore.QRect(690, 570, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exitButton.setFont(font)
        self.exitButton.setCheckable(False)
        self.exitButton.setAutoRepeat(False)
        self.exitButton.setAutoExclusive(False)
        self.exitButton.setObjectName("exitButton")
        self.runButton = QtWidgets.QPushButton(main)
        self.runButton.setGeometry(QtCore.QRect(970, 10, 81, 61))
        self.runButton.setCheckable(False)
        self.runButton.setAutoRepeat(False)
        self.runButton.setAutoExclusive(False)
        self.runButton.setObjectName("runButton")
        self.titleLabel = QtWidgets.QLabel(main)
        self.titleLabel.setGeometry(QtCore.QRect(680, -10, 271, 91))
        self.titleLabel.setObjectName("titleLabel")
        self.helpButton = QtWidgets.QPushButton(main)
        self.helpButton.setGeometry(QtCore.QRect(970, 80, 81, 31))
        self.helpButton.setCheckable(False)
        self.helpButton.setAutoRepeat(False)
        self.helpButton.setAutoExclusive(False)
        self.helpButton.setObjectName("helpButton")
        self.textBrowser = QtWidgets.QTextBrowser(main)
        self.textBrowser.setGeometry(QtCore.QRect(680, 60, 281, 291))
        self.textBrowser.setObjectName("textBrowser")
        self.commandLine = QtWidgets.QLineEdit(main)
        self.commandLine.setGeometry(QtCore.QRect(680, 360, 241, 31))
        self.commandLine.setObjectName("commandLine")
        self.sendButton = QtWidgets.QPushButton(main)
        self.sendButton.setGeometry(QtCore.QRect(930, 360, 31, 31))
        self.sendButton.setText("")
        self.sendButton.setObjectName("sendButton")
        self.clearButton = QtWidgets.QPushButton(main)
        self.clearButton.setGeometry(QtCore.QRect(970, 120, 81, 61))
        self.clearButton.setCheckable(False)
        self.clearButton.setAutoRepeat(False)
        self.clearButton.setAutoExclusive(False)
        self.clearButton.setObjectName("clearButton")
        self.openButton = QtWidgets.QPushButton(main)
        self.openButton.setGeometry(QtCore.QRect(970, 190, 81, 61))
        self.openButton.setCheckable(False)
        self.openButton.setAutoRepeat(False)
        self.openButton.setAutoExclusive(False)
        self.openButton.setObjectName("openButton")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Form"))
        self.save_py_select.setText(_translate("main", ".py"))
        self.save_mdw_select.setText(_translate("main", ".mdw"))
        self.saveButton.setText(_translate("main", "Guardar"))
        self.exitButton.setText(_translate("main", "Salir"))
        self.runButton.setText(_translate("main", "Ejecutar"))
        self.titleLabel.setText(_translate("main", "MDW  NoCodePython"))
        self.helpButton.setText(_translate("main", "Ayuda 🆘"))
        self.clearButton.setText(_translate("main", "Limpiar"))
        self.openButton.setText(_translate("main", "Abrir"))
